version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "6006:6006" 
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true